* The HotGlue spec
** Objects
*** Object Declaration
- An object is declared using ~ident: description~, within any scope.
- Applying multiple descriptions ~ident: descr_1: descr_2: ...~ is possible, if ~descr_1~ >= ~descr_2~ >= ~...~.
  For example ~a: u64: u32: 5~ is well defined and ~a: u32: u64: 3~ isn't.
  - However, the type of ~ident~ will still be ~descr_1~ and the value of ~ident~ will be ~descr_N~.
    All "in between" descriptions, are simple there for ensuring the inequality above.
  - if the description forms a fully defined object, for example ~a: 362~, then the object will become
    an unchangable constant. Use ~a: s32 = 362~ to create a variable of that type. Note how variables,
    unlike constants, need an explicit type.
    
**** Arrays
- Declare an array using ~ident : description[x]~ where ~x > 0~. ~x~ can be entirely excluded, to declare a
  one dimensional array of unspecified length.
- Multidimensional arrays can be defined as well, using ~ident: description[x][y]...~
- An array is fully defined, once its size is known and it has either the ~extern~ signifier or concrete values.
  
**** Object Signifiers
Put them in front of the identifier: ~signifier ident: description~.
| ~type~         | The object is just a type, it can't be modified, and won't be part of the data in the object. |
| ~extern~       | The object is not store inside HotGlue and therefore not directly accessable.                 |
| ~exr~          | The object is accessable from inside HotGlue, but will be read externally.                    |
| ~exw~          | As above, but will be written to externally.                                                  |
| ~exlayout SoA~ | If the object is a HotGlue array of external objects, the external layout will be SoA.        |
| ~exlayout AoS~ | As above, but the layout will be AoS.                                                         |

**** On Requirements
- Pose requirements on the creation of objects using ~ident: description req requirement~.
- The object cannot be created if the ~requirement~ evaluates to ~false~.
  This can cause *runtime errors*, when a value of external origin is used somewhere.
- ~requirement~ is still inside the scope of description, so ~this~ would evaluate to ~ident~.
  
**** On Identifiers
- Every object has an identifier which must be unique inside the scope.
- If identifiers from enclosing scopes collide, then the most recent identifier will *overshadow* the older identifier.
- It is legal to declare an object with the same name as the object it is declared as.
  For example ~Time: Time~ or the equivalent ~Time: this~.
  Note that any declaration, inside that scope, of the form ~ident: Time~ will now reference the ~Time: Time~ object.
  
**** On the ~description~
There are two types of objects, data objects and function objects.
- *Declare a data objects* using ~ident: {x}~ where ~x~ is a set of object declarations.
- *Declare a function object* using ~ident: (x){y}->{z}~ where ~x~ are the arguments to the function,
  ~y~ is the procedure where the functionality is implemented and ~z~ is the set of objects which will be returned.
  
**** On Defined vs. Undefined
***** Undefined when:
- Any object inside it, is undefined.
- There are any variables either without concrete values or without the ~extern~ signifier.
***** Examples
| ~a: i32~        | undefined |
| ~b: i32: 345~   | defined   |
| ~c: { a b }~    | undefined |
| ~extern d: f64~ | defined   |
| ~e:(){}->{4}~   | defined   |
| ~f:(_){}->{4}~  | undefined |
In the last example, a *placeholder* is used, to indicate that the arguments are indeed missing.

*** Data Objects
- Contains a set of data objects, function objects or unnamed self-activating procedures,
  which require access to the objects of the data object.
- Everything inside the data object, must be *fully defined*.
  
*** Function Objects
~ident: (args) {procedure} -> {object}~
- Everything inside the function object, must be *fully defined*.
**** ~args~
- *The arguments* of the function objects can be function and/or data objects.
  They must be *seperated by semicolons*.
- Assert additional requirements on any argument using ~req~ as in ~arg req requirement~,
  where ~requirement~ is a boolean expression.
**** ~procedure~
- Funcion objects *can't have sideeffects*. They cannot access any objects inside their ~procedure~ ([[*Procedures][Procedures]]),
  which were not declared inside the funciton object, or passed in as argument.
**** ~object~
- Function Objects return the Data Object defined or mentioned in their ~->{}~ structure, if provided with the
  correct arguments, using ~funv_obj(param_1, param_2, ...)~.
- ~object~ can also be an unnamed object, like the result of an expression. For example ~->{a + b}~.
- All objects which are passed in ~args~, but not returned in ~object~, will be consumed/lost.
***** ~to~
- Use the ~object_A to function_object_B~ to force a concatination of the current function object
  to ~function_object_B~, where ~object_A~ is an argument to ~function_object_B~.
  
*** Object instantiation
- To create a data object (or type) ~A~ *from another data object or data type* ~B~, simply declare ~A: B~.
  Use ~A: B { item_in_B: 5 }~ to access and further narrow the definition of the objects inside the instance of ~B~
  which then becomes ~A~.
- To create a data object (or type) ~A~ *from a function object* ~B~, use ~A: B(args)~, where ~args~
  is a list of the required arguments, which are again seperated by semicolons.
- It is not possible to create a function object from a function object (as in currying).
  
*** Assigning a value
- For assigning a value to a variable use ~a = value~, where the condition ~value < a~ must be satisfied.

** Procedures
- Procedures are ordered sets of actionable statements such as ~a = b~. They will be executed in the
  order they were declared in.
- They can't contain any object declarations, such that there are no temporary objects.
  
** Scopes
- A scope is the whole description of an object definition.
- Objects in enclosing scopes can be accessed from within the enclosed scope, if they were declared before that scope.
- The ~this~ keyword can be used in place of the identifier of the current scope.
- Scopes are produced by [[*Object Declaration][declarations]], [[*The ~expand~ Structure][expands]] and [[*The ~trigger~ Keyword][triggers]].
  
** Types
- Declare types using the ~type~ signifier.
- Types become objects, as soon as they have a clear representation in memory,
  unless they were declared with the ~type~ signifier.
- Types can be [[*Boolean set ops][compared]].
- There are types of function objects or data objects.
- [[*Examples][Examples]], everything which is *undefined* is a type, and not an object.
  
** Set Operations
- Most set operations can be evaluated in the first compiler pass.
- They must be evaluated in a following pass, if they involve the ~from all~ structure.
- They must be evaluated at runtime, if they involve the ~where~ keyword, such that it depends on variables
  which are not constant and fully defined.
  
*** Set Creation
| *op*        | *description*                                                                       | *requirement*       |
|-------------+-------------------------------------------------------------------------------------+---------------------|
| ~all~       | the set that contains all *objects* (no types) in global space                      |                     |
| ~a.b~       | *type* ~b~ from within *type* ~a~                                                   | ~b~ is ident        |
| ~a.~        | all *objects* (no types) from within ~a~                                            |                     |
| ~a.[b]~     | *object* at index ~b~ from within *object* ~a~                                      | ~b~ is integer      |
| ~a.all~     | all *objects* down from ~a~ recursively                                             |                     |
| ~a\b~       | ~b~ from within the *object or type*, which contains ~a~                            |                     |
| ~a\~        | all *objects* from within the object, which contains ~a~                            | ~b~ is ident        |
| ~a\all~     | all *objects* up from the object recursively, which contains ~a~                    |                     |
| ~a\this~    | the *object or type* that contains ~a~                                              |                     |
| ~a from b~  | all *objects* of type ~a~ in the set ~b~                                            | ~a~ is ident        |
| ~a where b~ | all *objects* in the set ~a~ for which the boolean expression ~b~ evaluates to true | ~b~ is boolean expr |
| ~last a~    | the *object*                                                                        |                     |

*** Boolean set ops
These work *on Types and on Objects*.
| ~==~     | are sets euqual?                               |
| ~!=~     | are sets not equal?                            |
| ~a > b~  | is ~b~ contained in ~a~, but not equal to ~a~? |
| ~a >= b~ | is ~b~ contained in ~a~?                       |
| ~a < b~  | is ~a~ contained in ~b~, but not equal to ~b~? |
| ~a <= b~ | is ~a~ contained in ~b~?                       |

*** Mathematical set ops
These work *only on Objects*.

**** Requirements
- Identical memory layout (and identical base types).
- No ~str~ or ~ident~ types.
- No ~extern~ objects.
  
**** Supported ops
| *op*         | *description*                 | *requirement*               |
|--------------+-------------------------------+-----------------------------|
| ~a + b~      | add ~b~ to ~a~                |                             |
| ~a - b~      | sub ~b~ from ~a~              |                             |
| ~a * b~      | mul ~a~ with ~b~              |                             |
| ~a / b~      | div ~a~ by ~b~                |                             |
| ~a ** b~     | pow ~a~ to ~b~                |                             |
| ~a % b~      | mod ~a~ by ~b~                | only Integer                |
| ~a = b~      | ~a~ update ~b~                | non const ~a~               |
| ~a =+ b~     | ~a~ update add ~b~            | non const ~a~               |
| ~a =- b~     | ~a~ update sub ~b~            | non const ~a~               |
| ~a =* b~     | ~a~ update mul ~b~            | non const ~a~               |
| ~a =/ b~     | ~a~ update div ~b~            | non const ~a~               |
| ~a =** b~    | ~a~ update pow ~b~            | non const ~a~               |
| ~a =% b~     | ~a~ update mod ~b~            | only Integer, non const ~a~ |
| ~sum(a)~     | sum of all elements  ~a~      |                             |
| ~product(a)~ | procut of all elements in ~a~ |                             |

** Symbolic Math
- Using any of the [[*Boolean set ops][Boolean set ops]], equations can be formulated,
  if the expression contains a single ~ident: symbol~ declaration, for example ~5 + 8 == x: symbol~.
- The declared symbol can then be accessed inside that scope.
- *Symbols do not belong to the object*, they are just helper variables.

** Syntax Sugar

*** The ~expand~ Structure
- Expand is used for compactly declaring many (similar) objects.
- There is no guaranteed order for the declaration, therefore they need to be independent, because
  ~expand~ operates on an unordered set, instead of on an iterator.
- Use ~expand(ident: description: set) { declaration }~ where ~set~ is a set of objects of ~description~,
  such that ~set~ >= ~description~ and ~description~ <= ~set~. Since ~ident~ would then be *overdefined*, ~expand~
  will pratically assign different versions of ~ident~ to different elements in ~set~ and generate declarations from
  ~declaration~ for all versions of ~ident~.
- A not completely defined ~ident~ object, would also be a valid set (for example ~t: u64~). Using ~req~ the set can be
  constrained without specifying an explicit set. For example ~expand (t: u64 req t < 10000) { do_something(t)}~, would
  expand over all integers in the range [0, 10000).
- The ~expand~ structure will form its own [[*Scopes][scope]].
  
*** The ~using~ Keyword
- Use ~using expression~ where expression contains ~_~ at least once, inside a scope, to replace all
  identifiers that follow the ~using~ declaration with the expression where the identifier replaces ~_~.
- If a using declaration follows a previous one, then the effect of the previous declaration will be terminated.
  Therefore a using declaration can be limited to a certain space with ~using expression ident_a ident_b using _~.

** Importing other HotGlue files
- Use ~include "source_file"~ to include the HotGlue objects in the global namespace However
  you have to avoid name collisions to other HotGlue objects from other files.
- Use ~ident: include "source_file"~ to include the HotGlue objects into their own namespace.
  They would then be adessed as ~ident.object~.

** Importing C, CUDA and OpenCL functions
- Use ~extern include "source_file"~ to import external functions from the source file (.c, .cu, ...),
  into the global name space.
- Use ~ident: extern include "source_file"~ to import external functions into their own namespace.
  The functions would then be adressed as ~ident.function_name~.

** Calling C, CUDA and OpenCL functions
- Use ~fun_signifier function_name(args)(const_args)~ to call an external function.
  The external source, containing the function must be [[*Importing C, CUDA and OpenCL functions][importet]].
- There exist [[*Call Signifiers][3 signifiers]] which can be used inplace of ~fun_signifier~. The are:
  | ~funC~    | call a C function    |
  | ~funCUDA~ | call a CUDA kernel   |
  | ~funOCL~  | call a OpenCL kernel |
- ~function_name~ must match the name of the function in the source code.
- ~args~ must be translatable to the functions native types. They are the true function arguments.
  - All args are passed as pointers by default. Specify passing by value using ~$arg~.
- ~const_args~, which is optional and can be excluded (parenthesis as well), are compile time constants,
  which may be used by the function. They will be put in const memory or in preprocessor macros.
  - Only objects with the signifier ~|~ will be selected form the ~const_args~ which are passed in.
  - The case ~| a: { | b: c}~ will be treated as ~| a: { b: c}~. ~a~ would be stored as C struct,
    such that ~b~ would be adressed as ~a.b~.
- C functions "collapse" into their return values, if they return anything. This value can for example
  be assigned to an appropriate object.
  
** The ~trigger~ Keyword
- Use ~trigger (expression) {procedure}~, where ~expression~ can be a either a boolean expression or a
  an expression resulting in any value and ~procedure~ is a set of actions to be performed.
- The ~procedure~ ([[*Procedures][Procedures]]) will be triggered, when the boolean expression *switches* to true, or when the
  non boolean expression *changes it's value*.

** The ~do~ Keyword
- Use ~do procedure~ to actually do what is described in the ~procedure~.
  HotGlue will figure out how to obtain the objects, which are used in the procedure.
- Usually calls an external procedure, which takes over control.
- The external procedure may terminate HotGlue, or change objects with the ~exw~ signifier.
  
** The ~exit~ Keyword
- Use ~exit~ to terminate the script. Any HotGlue file without the exit keyword will execute in interactive mode,
  until the user enters the ~exit~ keyword.
- If there is no ~exit~ in a HotGlue file, the compiler won't know, which statements may follow and therefore which
  objects should be kept around. Therefore, it can't free any memory resources.

** Base Types
- The native types of HotGlue.
| *HotGlue-type* | *as C-type*              | *as CUDA-type* | *as OpenCl-type* |
|----------------+--------------------------+----------------+------------------|
| ~i8~           | ~signed char~            | =              | =                |
| ~i16~          | ~signed short~           | =              | =                |
| ~i32~          | ~int~                    | =              | =                |
| ~i64~          | ~long long int~          | =              | =                |
| ~u8~           | ~unsinged char~          | =              | =                |
| ~u16~          | ~unsigned short~         | =              | =                |
| ~u32~          | ~unsigned int~           | =              | =                |
| ~u64~          | ~unsigned long long int~ | =              | =                |
| ~f8~           | -                        | ~fp8~          | ?                |
| ~f16~          | -                        | ~__half~       | ~half~           |
| ~f32~          | ~float~                  | =              | =                |
| ~f64~          | ~double~                 | =              | =                |

** Helper functions
*** ~size~
- Use ~size(object)~ to get the element count of that object (the count of the first layer).
- ~size()~ returns a value of type ~u64~.
**** Exception Handling
- if ~object~ is not an object type, a type error will be evoked and ~size()~ will evaluate to ~0~.
